// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TorrentFlow.Data;

#nullable disable

namespace TorrentFlow.Data.Migrations
{
    [DbContext(typeof(TorrentFlowDbContext))]
    [Migration("20260926032924_AddRequestGrabbedHashes")]
    partial class AddRequestGrabbedHashes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("TorrentFlow.Data.Entities.AcquisitionTarget", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("Episode")
                        .HasColumnType("INTEGER")
                        .HasColumnName("episode");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT")
                        .HasColumnName("error");

                    b.Property<string>("FilePath")
                        .HasColumnType("TEXT")
                        .HasColumnName("filePath");

                    b.Property<string>("InfoHash")
                        .HasColumnType("TEXT")
                        .HasColumnName("infoHash");

                    b.Property<int?>("PreferredResolution")
                        .HasColumnType("INTEGER")
                        .HasColumnName("preferredResolution");

                    b.Property<double>("Progress")
                        .HasColumnType("REAL")
                        .HasColumnName("progress");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("scope");

                    b.Property<int?>("Season")
                        .HasColumnType("INTEGER")
                        .HasColumnName("season");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("queued")
                        .HasColumnName("status");

                    b.Property<string>("TargetKey")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("targetKey");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("DATETIME")
                        .HasColumnName("updatedAt");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("userId");

                    b.Property<string>("WorkId")
                        .HasColumnType("TEXT")
                        .HasColumnName("workId");

                    b.Property<string>("WorkKey")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("workKey");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "UserId", "InfoHash" }, "AcquisitionTarget_userId_infoHash_idx");

                    b.HasIndex(new[] { "UserId", "Status" }, "AcquisitionTarget_userId_status_idx");

                    b.HasIndex(new[] { "UserId", "TargetKey" }, "AcquisitionTarget_userId_targetKey_key")
                        .IsUnique();

                    b.HasIndex(new[] { "UserId", "WorkKey", "Scope" }, "AcquisitionTarget_userId_workKey_scope_idx");

                    b.HasIndex(new[] { "WorkId" }, "AcquisitionTarget_workId_idx");

                    b.ToTable("AcquisitionTarget", (string)null);
                });

            modelBuilder.Entity("TorrentFlow.Data.Entities.AutoRule", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("all")
                        .HasColumnName("category");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BOOLEAN")
                        .HasColumnName("enabled")
                        .HasDefaultValueSql("true");

                    b.Property<string>("LastMatchMagnet")
                        .HasColumnType("TEXT")
                        .HasColumnName("lastMatchMagnet");

                    b.Property<string>("LastMatchTitle")
                        .HasColumnType("TEXT")
                        .HasColumnName("lastMatchTitle");

                    b.Property<string>("LastRunAt")
                        .HasColumnType("DATETIME")
                        .HasColumnName("lastRunAt");

                    b.Property<int>("MatchCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("matchCount");

                    b.Property<long?>("MaxSizeBytes")
                        .HasColumnType("BIGINT")
                        .HasColumnName("maxSizeBytes");

                    b.Property<int>("MinSeeders")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(10)
                        .HasColumnName("minSeeders");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Query")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("query");

                    b.Property<string>("Resolution")
                        .HasColumnType("TEXT")
                        .HasColumnName("resolution");

                    b.Property<string>("Sources")
                        .HasColumnType("TEXT")
                        .HasColumnName("sources");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("DATETIME")
                        .HasColumnName("updatedAt");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("userId");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "UserId", "Enabled" }, "AutoRule_userId_enabled_idx");

                    b.ToTable("AutoRule", (string)null);
                });

            modelBuilder.Entity("TorrentFlow.Data.Entities.CachedMetadatum", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("BackdropUrl")
                        .HasColumnType("TEXT")
                        .HasColumnName("backdropUrl");

                    b.Property<string>("CacheKey")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("cacheKey");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("ExpiresAt")
                        .IsRequired()
                        .HasColumnType("DATETIME")
                        .HasColumnName("expiresAt");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("externalId");

                    b.Property<string>("Genres")
                        .HasColumnType("TEXT")
                        .HasColumnName("genres");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("mediaType");

                    b.Property<string>("PosterUrl")
                        .HasColumnType("TEXT")
                        .HasColumnName("posterUrl");

                    b.Property<double?>("Rating")
                        .HasColumnType("REAL")
                        .HasColumnName("rating");

                    b.Property<string>("RawJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("rawJson");

                    b.Property<string>("ReleaseDate")
                        .HasColumnType("DATETIME")
                        .HasColumnName("releaseDate");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("source");

                    b.Property<string>("Synopsis")
                        .HasColumnType("TEXT")
                        .HasColumnName("synopsis");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("DATETIME")
                        .HasColumnName("updatedAt");

                    b.Property<int?>("Year")
                        .HasColumnType("INTEGER")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "CacheKey" }, "CachedMetadata_cacheKey_key")
                        .IsUnique();

                    b.HasIndex(new[] { "ExpiresAt" }, "CachedMetadata_expiresAt_idx");

                    b.HasIndex(new[] { "Source", "ExternalId" }, "CachedMetadata_source_externalId_idx");

                    b.HasIndex(new[] { "UpdatedAt" }, "CachedMetadata_updatedAt_idx");

                    b.ToTable("CachedMetadata");
                });

            modelBuilder.Entity("TorrentFlow.Data.Entities.CatalogEntry", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("BackdropUrl")
                        .HasColumnType("TEXT")
                        .HasColumnName("backdropUrl");

                    b.Property<string>("BestRelease")
                        .HasColumnType("TEXT")
                        .HasColumnName("bestRelease");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("mediaType");

                    b.Property<string>("Overview")
                        .HasColumnType("TEXT")
                        .HasColumnName("overview");

                    b.Property<string>("PosterUrl")
                        .HasColumnType("TEXT")
                        .HasColumnName("posterUrl");

                    b.Property<int>("Rank")
                        .HasColumnType("INTEGER")
                        .HasColumnName("rank");

                    b.Property<double?>("Rating")
                        .HasColumnType("REAL")
                        .HasColumnName("rating");

                    b.Property<string>("RefreshedAt")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME")
                        .HasColumnName("refreshedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("ReleaseDate")
                        .HasColumnType("DATETIME")
                        .HasColumnName("releaseDate");

                    b.Property<string>("SeedTitle")
                        .HasColumnType("TEXT")
                        .HasColumnName("seedTitle");

                    b.Property<int>("Seeders")
                        .HasColumnType("INTEGER")
                        .HasColumnName("seeders");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("source");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<string>("WorkId")
                        .HasColumnType("TEXT")
                        .HasColumnName("workId");

                    b.Property<string>("WorkKey")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("workKey");

                    b.Property<int?>("Year")
                        .HasColumnType("INTEGER")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "RefreshedAt" }, "CatalogEntry_refreshedAt_idx");

                    b.HasIndex(new[] { "Source", "Rank" }, "CatalogEntry_source_rank_idx");

                    b.HasIndex(new[] { "Source", "SeedTitle", "Rank", "Title" }, "CatalogEntry_source_seedTitle_rank_title_idx");

                    b.HasIndex(new[] { "WorkId" }, "CatalogEntry_workId_idx");

                    b.HasIndex(new[] { "WorkKey", "Source", "SeedTitle" }, "CatalogEntry_workKey_source_seedTitle_key")
                        .IsUnique();

                    b.ToTable("CatalogEntry", (string)null);
                });

            modelBuilder.Entity("TorrentFlow.Data.Entities.ClientSetting", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<int?>("AutomationIntervalMinutes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("automationIntervalMinutes");

                    b.Property<string>("BaseDownloadPath")
                        .HasColumnType("TEXT")
                        .HasColumnName("baseDownloadPath");

                    b.Property<string>("Categories")
                        .HasColumnType("TEXT")
                        .HasColumnName("categories");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT")
                        .HasColumnName("category");

                    b.Property<string>("ClientType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("builtin")
                        .HasColumnName("clientType");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DefaultRetentionPolicy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("EPHEMERAL")
                        .HasColumnName("defaultRetentionPolicy");

                    b.Property<string>("DownloadWindows")
                        .HasColumnType("TEXT")
                        .HasColumnName("downloadWindows");

                    b.Property<string>("ExternalClientType")
                        .HasColumnType("TEXT")
                        .HasColumnName("externalClientType");

                    b.Property<string>("Host")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("http://127.0.0.1:8080")
                        .HasColumnName("host");

                    b.Property<int?>("MaxActiveDownloads")
                        .HasColumnType("INTEGER")
                        .HasColumnName("maxActiveDownloads");

                    b.Property<long?>("MaxStorageBytes")
                        .HasColumnType("BIGINT")
                        .HasColumnName("maxStorageBytes");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT")
                        .HasColumnName("password");

                    b.Property<string>("PathRules")
                        .HasColumnType("TEXT")
                        .HasColumnName("pathRules");

                    b.Property<string>("PreProbeScope")
                        .HasColumnType("TEXT")
                        .HasColumnName("preProbeScope");

                    b.Property<int?>("PreferredResolution")
                        .HasColumnType("INTEGER")
                        .HasColumnName("preferredResolution");

                    b.Property<string>("SavePath")
                        .HasColumnType("TEXT")
                        .HasColumnName("savePath");

                    b.Property<bool?>("StorageCapConfigured")
                        .HasColumnType("BOOLEAN")
                        .HasColumnName("storageCapConfigured");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("DATETIME")
                        .HasColumnName("updatedAt");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("userId");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT")
                        .HasColumnName("username");

                    b.Property<bool?>("VerboseDiagnostics")
                        .HasColumnType("BOOLEAN")
                        .HasColumnName("verboseDiagnostics");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "UserId" }, "ClientSettings_userId_key")
                        .IsUnique();

                    b.ToTable("ClientSettings");
                });

            modelBuilder.Entity("TorrentFlow.Data.Entities.DownloadHistory", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT")
                        .HasColumnName("category");

                    b.Property<string>("ClientType")
                        .HasColumnType("TEXT")
                        .HasColumnName("clientType");

                    b.Property<string>("Context")
                        .HasColumnType("TEXT")
                        .HasColumnName("context");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("InfoHash")
                        .HasColumnType("TEXT")
                        .HasColumnName("infoHash");

                    b.Property<string>("Magnet")
                        .HasColumnType("TEXT")
                        .HasColumnName("magnet");

                    b.Property<string>("Message")
                        .HasColumnType("TEXT")
                        .HasColumnName("message");

                    b.Property<string>("Retention")
                        .HasColumnType("TEXT")
                        .HasColumnName("retention");

                    b.Property<string>("SavePath")
                        .HasColumnType("TEXT")
                        .HasColumnName("savePath");

                    b.Property<string>("SendKind")
                        .HasColumnType("TEXT")
                        .HasColumnName("sendKind");

                    b.Property<string>("Source")
                        .HasColumnType("TEXT")
                        .HasColumnName("source");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<string>("TorrentUrl")
                        .HasColumnType("TEXT")
                        .HasColumnName("torrentUrl");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("userId");

                    b.Property<string>("WorkId")
                        .HasColumnType("TEXT")
                        .HasColumnName("workId");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "UserId", "CreatedAt" }, "DownloadHistory_userId_createdAt_idx");

                    b.HasIndex(new[] { "UserId", "Status" }, "DownloadHistory_userId_status_idx");

                    b.HasIndex(new[] { "WorkId" }, "DownloadHistory_workId_idx");

                    b.ToTable("DownloadHistory", (string)null);
                });

            modelBuilder.Entity("TorrentFlow.Data.Entities.EngineTorrent", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT")
                        .HasColumnName("category");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT")
                        .HasColumnName("error");

                    b.Property<string>("EvictFrom")
                        .HasColumnType("TEXT")
                        .HasColumnName("evictFrom");

                    b.Property<string>("EvictLease")
                        .HasColumnType("TEXT")
                        .HasColumnName("evictLease");

                    b.Property<string>("ForcedAt")
                        .HasColumnType("DATETIME")
                        .HasColumnName("forcedAt");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("hash");

                    b.Property<int>("Lane")
                        .HasColumnType("INTEGER")
                        .HasColumnName("lane");

                    b.Property<string>("LastUsedAt")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME")
                        .HasColumnName("lastUsedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Magnet")
                        .HasColumnType("TEXT")
                        .HasColumnName("magnet");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("user")
                        .HasColumnName("origin");

                    b.Property<double>("Progress")
                        .HasColumnType("REAL")
                        .HasColumnName("progress");

                    b.Property<string>("QueueKey")
                        .HasColumnType("TEXT")
                        .HasColumnName("queueKey");

                    b.Property<string>("SavePath")
                        .HasColumnType("TEXT")
                        .HasColumnName("savePath");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("BIGINT")
                        .HasColumnName("sizeBytes");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("downloading")
                        .HasColumnName("status");

                    b.Property<string>("TorrentUrl")
                        .HasColumnType("TEXT")
                        .HasColumnName("torrentUrl");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("DATETIME")
                        .HasColumnName("updatedAt");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("userId");

                    b.Property<string>("VerifiedAt")
                        .HasColumnType("DATETIME")
                        .HasColumnName("verifiedAt");

                    b.Property<string>("VerifiedBitfield")
                        .HasColumnType("TEXT")
                        .HasColumnName("verifiedBitfield");

                    b.Property<string>("VerifiedFilesJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("verifiedFilesJson");

                    b.Property<string>("WorkId")
                        .HasColumnType("TEXT")
                        .HasColumnName("workId");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "UserId", "Hash" }, "EngineTorrent_userId_hash_key")
                        .IsUnique();

                    b.HasIndex(new[] { "UserId", "Origin", "LastUsedAt" }, "EngineTorrent_userId_origin_lastUsedAt_idx");

                    b.HasIndex(new[] { "UserId", "Status" }, "EngineTorrent_userId_status_idx");

                    b.HasIndex(new[] { "WorkId" }, "EngineTorrent_workId_idx");

                    b.ToTable("EngineTorrent", (string)null);
                });

            modelBuilder.Entity("TorrentFlow.Data.Entities.GrabJob", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT")
                        .HasColumnName("category");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("ExternalId")
                        .HasColumnType("TEXT")
                        .HasColumnName("externalId");

                    b.Property<string>("InfoHash")
                        .HasColumnType("TEXT")
                        .HasColumnName("infoHash");

                    b.Property<string>("Kind")
                        .HasColumnType("TEXT")
                        .HasColumnName("kind");

                    b.Property<string>("Magnet")
                        .HasColumnType("TEXT")
                        .HasColumnName("magnet");

                    b.Property<string>("Message")
                        .HasColumnType("TEXT")
                        .HasColumnName("message");

                    b.Property<string>("Query")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("query");

                    b.Property<string>("Retention")
                        .HasColumnType("TEXT")
                        .HasColumnName("retention");

                    b.Property<string>("SavePath")
                        .HasColumnType("TEXT")
                        .HasColumnName("savePath");

                    b.Property<string>("Source")
                        .HasColumnType("TEXT")
                        .HasColumnName("source");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("DATETIME")
                        .HasColumnName("updatedAt");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("userId");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "UserId", "CreatedAt" }, "GrabJob_userId_createdAt_idx");

                    b.HasIndex(new[] { "UserId", "Status" }, "GrabJob_userId_status_idx");

                    b.ToTable("GrabJob", (string)null);
                });

            modelBuilder.Entity("TorrentFlow.Data.Entities.MediaProbe", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<int?>("AudioChannels")
                        .HasColumnType("INTEGER")
                        .HasColumnName("audioChannels");

                    b.Property<string>("AudioCodec")
                        .HasColumnType("TEXT")
                        .HasColumnName("audioCodec");

                    b.Property<string>("AudioLayout")
                        .HasColumnType("TEXT")
                        .HasColumnName("audioLayout");

                    b.Property<int?>("BitRateBps")
                        .HasColumnType("INTEGER")
                        .HasColumnName("bitRateBps");

                    b.Property<string>("ColorTransfer")
                        .HasColumnType("TEXT")
                        .HasColumnName("colorTransfer");

                    b.Property<string>("Container")
                        .HasColumnType("TEXT")
                        .HasColumnName("container");

                    b.Property<double?>("DurationSec")
                        .HasColumnType("REAL")
                        .HasColumnName("durationSec");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("filePath");

                    b.Property<int?>("Height")
                        .HasColumnType("INTEGER")
                        .HasColumnName("height");

                    b.Property<string>("InfoHash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("infoHash");

                    b.Property<int>("ProbeVersion")
                        .HasColumnType("INTEGER")
                        .HasColumnName("probeVersion");

                    b.Property<string>("ProbedAt")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME")
                        .HasColumnName("probedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("StreamsJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("streamsJson");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("DATETIME")
                        .HasColumnName("updatedAt");

                    b.Property<string>("VideoCodec")
                        .HasColumnType("TEXT")
                        .HasColumnName("videoCodec");

                    b.Property<string>("VideoProfile")
                        .HasColumnType("TEXT")
                        .HasColumnName("videoProfile");

                    b.Property<int?>("Width")
                        .HasColumnType("INTEGER")
                        .HasColumnName("width");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "InfoHash", "FilePath" }, "MediaProbe_infoHash_filePath_key")
                        .IsUnique();

                    b.ToTable("MediaProbe", (string)null);
                });

            modelBuilder.Entity("TorrentFlow.Data.Entities.MediaRequest", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("AcquisitionTargetId")
                        .HasColumnType("TEXT")
                        .HasColumnName("acquisitionTargetId");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DecidedAt")
                        .HasColumnType("DATETIME")
                        .HasColumnName("decidedAt");

                    b.Property<string>("DecisionReason")
                        .HasColumnType("TEXT")
                        .HasColumnName("decisionReason");

                    b.Property<string>("GrabbedHashes")
                        .HasColumnType("TEXT")
                        .HasColumnName("grabbedHashes");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("mediaType");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT")
                        .HasColumnName("note");

                    b.Property<string>("PosterUrl")
                        .HasColumnType("TEXT")
                        .HasColumnName("posterUrl");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderId")
                        .HasColumnType("TEXT")
                        .HasColumnName("providerId");

                    b.Property<string>("RequestedByUserId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("requestedByUserId");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("scope");

                    b.Property<string>("Seasons")
                        .HasColumnType("TEXT")
                        .HasColumnName("seasons");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("pending")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("DATETIME")
                        .HasColumnName("updatedAt");

                    b.Property<string>("WatchListItemId")
                        .HasColumnType("TEXT")
                        .HasColumnName("watchListItemId");

                    b.Property<string>("WorkKey")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("workKey");

                    b.Property<int?>("Year")
                        .HasColumnType("INTEGER")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.HasIndex("AcquisitionTargetId");

                    b.HasIndex("WatchListItemId");

                    b.HasIndex(new[] { "RequestedByUserId", "Status" }, "MediaRequest_requestedByUserId_status_idx");

                    b.HasIndex(new[] { "Status", "CreatedAt" }, "MediaRequest_status_createdAt_idx");

                    b.HasIndex(new[] { "WorkKey" }, "MediaRequest_workKey_idx");

                    b.ToTable("MediaRequest", (string)null);
                });

            modelBuilder.Entity("TorrentFlow.Data.Entities.PlaybackProgress", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CompletedAt")
                        .HasColumnType("DATETIME")
                        .HasColumnName("completedAt");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<double?>("DurationSec")
                        .HasColumnType("REAL")
                        .HasColumnName("durationSec");

                    b.Property<int?>("Episode")
                        .HasColumnType("INTEGER")
                        .HasColumnName("episode");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("filePath");

                    b.Property<string>("InfoHash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("infoHash");

                    b.Property<double>("PositionSec")
                        .HasColumnType("REAL")
                        .HasColumnName("positionSec");

                    b.Property<string>("PosterUrl")
                        .HasColumnType("TEXT")
                        .HasColumnName("posterUrl");

                    b.Property<int?>("Season")
                        .HasColumnType("INTEGER")
                        .HasColumnName("season");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("DATETIME")
                        .HasColumnName("updatedAt");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("userId");

                    b.Property<string>("WatchListItemId")
                        .HasColumnType("TEXT")
                        .HasColumnName("watchListItemId");

                    b.Property<string>("WorkId")
                        .HasColumnType("TEXT")
                        .HasColumnName("workId");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "UserId", "CompletedAt" }, "PlaybackProgress_userId_completedAt_idx");

                    b.HasIndex(new[] { "UserId", "InfoHash", "FilePath" }, "PlaybackProgress_userId_infoHash_filePath_key")
                        .IsUnique();

                    b.HasIndex(new[] { "UserId", "UpdatedAt" }, "PlaybackProgress_userId_updatedAt_idx");

                    b.HasIndex(new[] { "WorkId" }, "PlaybackProgress_workId_idx");

                    b.ToTable("PlaybackProgress", (string)null);
                });

            modelBuilder.Entity("TorrentFlow.Data.Entities.RunLock", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("AcquiredAt")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME")
                        .HasColumnName("acquiredAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("scope");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("userId");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "AcquiredAt" }, "RunLock_acquiredAt_idx");

                    b.HasIndex(new[] { "UserId", "Scope" }, "RunLock_userId_scope_key")
                        .IsUnique();

                    b.ToTable("RunLock", (string)null);
                });

            modelBuilder.Entity("TorrentFlow.Data.Entities.SearchCache", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CacheKey")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("cacheKey");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("ExpiresAt")
                        .IsRequired()
                        .HasColumnType("DATETIME")
                        .HasColumnName("expiresAt");

                    b.Property<string>("NormalizedQuery")
                        .HasColumnType("TEXT")
                        .HasColumnName("normalizedQuery");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("payload");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "CacheKey" }, "SearchCache_cacheKey_key")
                        .IsUnique();

                    b.HasIndex(new[] { "ExpiresAt" }, "SearchCache_expiresAt_idx");

                    b.HasIndex(new[] { "NormalizedQuery", "ExpiresAt" }, "SearchCache_normalizedQuery_expiresAt_idx");

                    b.ToTable("SearchCache", (string)null);
                });

            modelBuilder.Entity("TorrentFlow.Data.Entities.SwarmMeasurement", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<long>("BytesReceived")
                        .HasColumnType("BIGINT")
                        .HasColumnName("bytesReceived");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<double>("EffectiveBps")
                        .HasColumnType("REAL")
                        .HasColumnName("effectiveBps");

                    b.Property<int>("ElapsedMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("elapsedMs");

                    b.Property<string>("ExpiresAt")
                        .IsRequired()
                        .HasColumnType("DATETIME")
                        .HasColumnName("expiresAt");

                    b.Property<string>("InfoHash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("infoHash");

                    b.Property<string>("MeasuredAt")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME")
                        .HasColumnName("measuredAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int>("PeersConnected")
                        .HasColumnType("INTEGER")
                        .HasColumnName("peersConnected");

                    b.Property<int>("PeersUnchoked")
                        .HasColumnType("INTEGER")
                        .HasColumnName("peersUnchoked");

                    b.Property<double>("RequiredBps")
                        .HasColumnType("REAL")
                        .HasColumnName("requiredBps");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("DATETIME")
                        .HasColumnName("updatedAt");

                    b.Property<string>("Verdict")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("verdict");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ExpiresAt" }, "SwarmMeasurement_expiresAt_idx");

                    b.HasIndex(new[] { "InfoHash" }, "SwarmMeasurement_infoHash_key")
                        .IsUnique();

                    b.ToTable("SwarmMeasurement", (string)null);
                });

            modelBuilder.Entity("TorrentFlow.Data.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<string>("Image")
                        .HasColumnType("TEXT")
                        .HasColumnName("image");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("DATETIME")
                        .HasColumnName("updatedAt");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Email" }, "User_email_key")
                        .IsUnique();

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("TorrentFlow.Data.Entities.WatchListItem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("CursorEpisode")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cursorEpisode");

                    b.Property<int>("CursorMisses")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cursorMisses");

                    b.Property<int?>("CursorSeason")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cursorSeason");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("externalId");

                    b.Property<int?>("FromEpisode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1)
                        .HasColumnName("fromEpisode");

                    b.Property<int?>("FromSeason")
                        .HasColumnType("INTEGER")
                        .HasColumnName("fromSeason");

                    b.Property<string>("LastChecked")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME")
                        .HasColumnName("lastChecked")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("LastEpisode")
                        .HasColumnType("TEXT")
                        .HasColumnName("lastEpisode");

                    b.Property<string>("LatestReleaseAt")
                        .HasColumnType("DATETIME")
                        .HasColumnName("latestReleaseAt");

                    b.Property<string>("LatestReleaseMagnet")
                        .HasColumnType("TEXT")
                        .HasColumnName("latestReleaseMagnet");

                    b.Property<string>("LatestReleaseTitle")
                        .HasColumnType("TEXT")
                        .HasColumnName("latestReleaseTitle");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("mediaType");

                    b.Property<string>("MonitorMode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("ongoing")
                        .HasColumnName("monitorMode");

                    b.Property<bool>("Monitored")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BOOLEAN")
                        .HasColumnName("monitored")
                        .HasDefaultValueSql("true");

                    b.Property<string>("NextCheckAt")
                        .HasColumnType("DATETIME")
                        .HasColumnName("nextCheckAt");

                    b.Property<string>("NextCheckReason")
                        .HasColumnType("TEXT")
                        .HasColumnName("nextCheckReason");

                    b.Property<string>("NextEpisodeHint")
                        .HasColumnType("TEXT")
                        .HasColumnName("nextEpisodeHint");

                    b.Property<string>("PosterUrl")
                        .HasColumnType("TEXT")
                        .HasColumnName("posterUrl");

                    b.Property<int?>("PreferredResolution")
                        .HasColumnType("INTEGER")
                        .HasColumnName("preferredResolution");

                    b.Property<double?>("Rating")
                        .HasColumnType("REAL")
                        .HasColumnName("rating");

                    b.Property<string>("SeederWaitSince")
                        .HasColumnType("DATETIME")
                        .HasColumnName("seederWaitSince");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("watching")
                        .HasColumnName("status");

                    b.Property<string>("Synopsis")
                        .HasColumnType("TEXT")
                        .HasColumnName("synopsis");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("DATETIME")
                        .HasColumnName("updatedAt");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("userId");

                    b.Property<string>("WorkId")
                        .HasColumnType("TEXT")
                        .HasColumnName("workId");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "UserId" }, "WatchListItem_userId_idx");

                    b.HasIndex(new[] { "UserId", "MediaType", "ExternalId" }, "WatchListItem_userId_mediaType_externalId_key")
                        .IsUnique();

                    b.HasIndex(new[] { "UserId", "NextCheckAt" }, "WatchListItem_userId_nextCheckAt_idx");

                    b.HasIndex(new[] { "WorkId" }, "WatchListItem_workId_idx");

                    b.ToTable("WatchListItem", (string)null);
                });

            modelBuilder.Entity("TorrentFlow.Data.Entities.Work", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("AliasesJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("aliasesJson");

                    b.Property<string>("CanonicalTitle")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("canonicalTitle");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("mediaType");

                    b.Property<string>("PosterUrl")
                        .HasColumnType("TEXT")
                        .HasColumnName("posterUrl");

                    b.Property<string>("Provider")
                        .HasColumnType("TEXT")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderId")
                        .HasColumnType("TEXT")
                        .HasColumnName("providerId");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("DATETIME")
                        .HasColumnName("updatedAt");

                    b.Property<string>("WorkKey")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("workKey");

                    b.Property<int?>("Year")
                        .HasColumnType("INTEGER")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "MediaType" }, "Work_mediaType_idx");

                    b.HasIndex(new[] { "Provider", "ProviderId", "MediaType" }, "Work_provider_providerId_mediaType_key")
                        .IsUnique();

                    b.HasIndex(new[] { "WorkKey" }, "Work_workKey_key")
                        .IsUnique();

                    b.ToTable("Work", (string)null);
                });

            modelBuilder.Entity("TorrentFlow.Data.Entities.AcquisitionTarget", b =>
                {
                    b.HasOne("TorrentFlow.Data.Entities.User", "User")
                        .WithMany("AcquisitionTargets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TorrentFlow.Data.Entities.Work", "Work")
                        .WithMany("AcquisitionTargets")
                        .HasForeignKey("WorkId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");

                    b.Navigation("Work");
                });

            modelBuilder.Entity("TorrentFlow.Data.Entities.AutoRule", b =>
                {
                    b.HasOne("TorrentFlow.Data.Entities.User", "User")
                        .WithMany("AutoRules")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TorrentFlow.Data.Entities.CatalogEntry", b =>
                {
                    b.HasOne("TorrentFlow.Data.Entities.Work", "Work")
                        .WithMany("CatalogEntries")
                        .HasForeignKey("WorkId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Work");
                });

            modelBuilder.Entity("TorrentFlow.Data.Entities.ClientSetting", b =>
                {
                    b.HasOne("TorrentFlow.Data.Entities.User", "User")
                        .WithOne("ClientSetting")
                        .HasForeignKey("TorrentFlow.Data.Entities.ClientSetting", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TorrentFlow.Data.Entities.DownloadHistory", b =>
                {
                    b.HasOne("TorrentFlow.Data.Entities.User", "User")
                        .WithMany("DownloadHistories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TorrentFlow.Data.Entities.Work", "Work")
                        .WithMany("DownloadHistories")
                        .HasForeignKey("WorkId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");

                    b.Navigation("Work");
                });

            modelBuilder.Entity("TorrentFlow.Data.Entities.EngineTorrent", b =>
                {
                    b.HasOne("TorrentFlow.Data.Entities.User", "User")
                        .WithMany("EngineTorrents")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TorrentFlow.Data.Entities.Work", "Work")
                        .WithMany("EngineTorrents")
                        .HasForeignKey("WorkId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");

                    b.Navigation("Work");
                });

            modelBuilder.Entity("TorrentFlow.Data.Entities.GrabJob", b =>
                {
                    b.HasOne("TorrentFlow.Data.Entities.User", "User")
                        .WithMany("GrabJobs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TorrentFlow.Data.Entities.MediaRequest", b =>
                {
                    b.HasOne("TorrentFlow.Data.Entities.AcquisitionTarget", null)
                        .WithMany()
                        .HasForeignKey("AcquisitionTargetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TorrentFlow.Data.Entities.User", "RequestedBy")
                        .WithMany("MediaRequests")
                        .HasForeignKey("RequestedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TorrentFlow.Data.Entities.WatchListItem", null)
                        .WithMany()
                        .HasForeignKey("WatchListItemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("RequestedBy");
                });

            modelBuilder.Entity("TorrentFlow.Data.Entities.PlaybackProgress", b =>
                {
                    b.HasOne("TorrentFlow.Data.Entities.User", "User")
                        .WithMany("PlaybackProgresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TorrentFlow.Data.Entities.Work", "Work")
                        .WithMany("PlaybackProgresses")
                        .HasForeignKey("WorkId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");

                    b.Navigation("Work");
                });

            modelBuilder.Entity("TorrentFlow.Data.Entities.WatchListItem", b =>
                {
                    b.HasOne("TorrentFlow.Data.Entities.User", "User")
                        .WithMany("WatchListItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TorrentFlow.Data.Entities.Work", "Work")
                        .WithMany("WatchListItems")
                        .HasForeignKey("WorkId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");

                    b.Navigation("Work");
                });

            modelBuilder.Entity("TorrentFlow.Data.Entities.User", b =>
                {
                    b.Navigation("AcquisitionTargets");

                    b.Navigation("AutoRules");

                    b.Navigation("ClientSetting");

                    b.Navigation("DownloadHistories");

                    b.Navigation("EngineTorrents");

                    b.Navigation("GrabJobs");

                    b.Navigation("MediaRequests");

                    b.Navigation("PlaybackProgresses");

                    b.Navigation("WatchListItems");
                });

            modelBuilder.Entity("TorrentFlow.Data.Entities.Work", b =>
                {
                    b.Navigation("AcquisitionTargets");

                    b.Navigation("CatalogEntries");

                    b.Navigation("DownloadHistories");

                    b.Navigation("EngineTorrents");

                    b.Navigation("PlaybackProgresses");

                    b.Navigation("WatchListItems");
                });
#pragma warning restore 612, 618
        }
    }
}
