overrides:
  deepmerge-ts: ^8.0.2
  mysql2: ^3.24.4

allowBuilds:
  "@prisma/engines": true
  bufferutil: true
  esbuild: true
  ffmpeg-static: true
  ip-set: true
  node-datachannel: true
  prisma: true
  unrs-resolver: true
  utf-8-validate: true
  utp-native: true
