<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="MonoTorrent" />
    <ProjectReference Include="..\TorrentFlow.Core\TorrentFlow.Core.csproj" />
    <ProjectReference Include="..\TorrentFlow.Data\TorrentFlow.Data.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="TorrentFlow.Engine.Tests" />
  </ItemGroup>
</Project>
