<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AnalysisLevel>latest-recommended</AnalysisLevel>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />


  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="TorrentFlow.Core.Tests" />
    <EmbeddedResource Include="Sources\sources.default.json" />
  </ItemGroup>
</Project>
