using System.Text.Json;
using TorrentFlow.Core.Contracts.Search;
using TorrentFlow.Library.Features.Grabs;
using TorrentFlow.Library.Features.Watchlist;

namespace TorrentFlow.Library.Tests;

/// <summary>
/// Table-driven parity against outputs captured from the TS original (TsOracle/ts-oracle.json, generated by
/// TsOracle/oracle.ts). Every row is a real-looking release name or catalog title run through both implementations.
/// </summary>
public sealed class LadderParityTests
{
    private static readonly JsonElement Oracle = JsonDocument.Parse(File.ReadAllText(Path.Combine(AppContext.BaseDirectory, "TsOracle", "ts-oracle.json"))).RootElement.Clone();
    private static IEnumerable<JsonElement> Section(string name) => Oracle.GetProperty(name).EnumerateArray();
    private static string[] Strings(JsonElement e) => e.EnumerateArray().Select(x => x.GetString()!).ToArray();
    private static int? Int(JsonElement e) => e.ValueKind == JsonValueKind.Null ? null : e.GetInt32();
    private static TorrentResult Result(string title, int seeders = 10, bool magnet = true) => new()
    {
        Id = title, Title = title, Magnet = magnet ? $"magnet:?xt=urn:btih:{title.Length}" : null, Seeders = seeders, Source = "nyaa", SourceUrl = ""
    };

    [Fact]
    public void EpisodeRungsMatchTsLadderOrder()
    {
        foreach (var row in Section("rungs"))
        {
            var input = row.GetProperty("input");
            var title = input[0].GetString()!;
            var rungs = EpisodeLadder.BuildEpisodeRungs(title, new EpisodeCursor(input[1].GetInt32(), input[2].GetInt32()), input[3].GetString(),
                Strings(input[4]), Int(input[5]));
            var expected = row.GetProperty("rungs").EnumerateArray().Select(r =>
                $"{r[0].GetString()}|{r[1].GetString()}|{r[2].GetString()}|{Int(r[3])}|{Int(r[4])}|{Int(r[5])}").ToArray();
            var actual = rungs.Select(r => $"{r.Kind}|{r.Query}|{r.Category}|{r.Filters.MinSeeders}|{r.Filters.Season}|{r.Filters.Episode}").ToArray();
            Assert.True(expected.SequenceEqual(actual), $"{title}\nexpected:\n{string.Join('\n', expected)}\nactual:\n{string.Join('\n', actual)}");
            Assert.All(rungs, r => Assert.Equal(r.Kind == "relaxed", r.Relaxed));
        }
    }

    [Fact]
    public void TitleVariantsAndAliasFormsMatchTs()
    {
        foreach (var row in Section("variants")) Assert.Equal(Strings(row[1]), EpisodeLadder.SearchTitleVariants(row[0].GetString()!));
        foreach (var row in Section("forms")) Assert.Equal(Strings(row[1]), EpisodeLadder.AliasTitleForms(row[0].GetString()!));
        Assert.Equal(Strings(Oracle.GetProperty("rank")),
            EpisodeLadder.RankAliases(["Shingeki no Kyojin", "進撃の巨人", "Attack on Titan: Final Season", "AoT", "ShingekiNoKyojin"]));
    }

    [Fact]
    public void TargetEpisodeMatchingMatchesTs()
    {
        EpisodeCursor[] targets = [new(1, 1), new(3, 5), new(2, 4), new(1, 7), new(5, 14), new(1, 3)];
        foreach (var row in Section("match"))
        {
            var title = row[0].GetString()!;
            var expected = row[1].EnumerateArray().Select(x => x.GetBoolean()).ToArray();
            Assert.True(expected.SequenceEqual(targets.Select(t => EpisodeLadder.MatchesTargetEpisode(Result(title), t))), title);
            Assert.True(row[2].GetBoolean() == ReleaseNames.IsEpisodeRangeRelease(title), title);
        }
    }

    [Fact]
    public void DisplayTitlesAndWorkIdentityMatchTs()
    {
        foreach (var row in Section("clean"))
        {
            var name = row[0].GetString()!;
            Assert.Equal(row[1].GetString(), ReleaseNames.CleanDisplayTitle(name));
            var identity = ReleaseNames.IdentityFor(name);
            var expected = row[2];
            Assert.Equal(expected.GetProperty("name").GetString(), identity.Name);
            Assert.Equal(Int(expected.GetProperty("year")), identity.Year);
            Assert.Equal(expected.GetProperty("isSeries").GetBoolean(), identity.IsSeries);
        }
    }

    [Fact]
    public void WorkKeysMatchTs()
    {
        foreach (var row in Section("keys"))
        {
            var identity = ReleaseNames.IdentityFor(row[1].GetString()!);
            Assert.True(row[2].GetBoolean() == ReleaseNames.WorkKeyMatches(row[0].GetString()!, identity.Name, identity.Year), $"{row[0]} vs {row[1]}");
        }
        foreach (var row in Section("workKeyFor")) Assert.Equal(row[2].GetString(), ReleaseNames.WorkKeyFor(row[0].GetString()!, Int(row[1])));
        foreach (var row in Section("workMatch"))
        {
            var release = Result(row[0].GetString()!);
            Assert.True(row[1].GetBoolean() == EpisodeLadder.ReleaseMatchesWork(release, ["Frieren: Beyond Journey's End", "Sousou no Frieren"]), $"frieren {release.Title}");
            Assert.True(row[2].GetBoolean() == EpisodeLadder.ReleaseMatchesWork(release, ["Attack on Titan", "Shingeki no Kyojin"]), $"aot {release.Title}");
            Assert.True(row[3].GetBoolean() == EpisodeLadder.ReleaseMatchesWork(release, ["Family Guy"]), $"family guy {release.Title}");
        }
    }

    [Fact]
    public void FilmSelectionAndMessagesMatchTs()
    {
        TorrentResult[] film = [Result("Children.of.Dune.2003.1080p", 90), Result("Dune.2021.720p.WEB", 80), Result("Dune.2021.1080p.BluRay.x264", 0),
            Result("Dune.2021.2160p.WEB-DL", 40, magnet: false), Result("Dune.2021.1080p.WEB-DL.DDP5.1", 30), Result("Dune.2021.S01.1080p", 20)];
        var select = Oracle.GetProperty("filmSelect");
        Assert.Equal(select[0].GetString(), FilmSelection.Select(film, "dune-2021", 1080)?.Title);
        Assert.Equal(select[1].GetString(), FilmSelection.Select(film, "dune-2021", 2160)?.Title);
        var summary = Oracle.GetProperty("filmSummary");
        Assert.Equal(new FilmRejection(summary.GetProperty("total").GetInt32(), summary.GetProperty("noMagnet").GetInt32(), summary.GetProperty("unseeded").GetInt32(),
            summary.GetProperty("belowFloor").GetInt32(), summary.GetProperty("otherWork").GetInt32(), summary.GetProperty("packOrEpisode").GetInt32()),
            FilmSelection.Summarize(film, "dune-2021", 1080));
        var messages = Strings(Oracle.GetProperty("filmMessages"));
        Assert.Equal(messages[0], FilmSelection.NoMatchMessage("Dune", 1080, 0, null, null));
        Assert.Equal(messages[1], FilmSelection.NoMatchMessage("Dune", 2160, 6, null, FilmSelection.Summarize(film, "dune-2021", 2160)));
        Assert.Equal(messages[2], FilmSelection.NoMatchMessage("Dune", null, 6, null, FilmSelection.Summarize(film, "dune-2021", null)));
        Assert.Equal(messages[3], FilmSelection.NoMatchMessage("Dune", 1080, 0, [new("nyaa", 0, "timeout"), new("tpb", 0, "503")], null));
        Assert.Equal(messages[4], FilmSelection.NoMatchMessage("Dune", 1080, 0, [new("nyaa", 0, "timeout"), new("tpb", 0)], null));
    }
}
